Programación para *Data Science*
============================

Intro101 - 07a Conceptos avanzados de Python
--------------------------------------

En este Notebook encontraréis dos conjuntos de ejercicios de Python.

### Ejercicio 1

Un número primo es aquél que solo es divisible por él mismo y por 1.

a) Escribe un código que compruebe si un número `x = 15` es solo divisible por 1 o por el mismo.  Escribe este código usando un iterador (un `for` o un `while`) que barra todos los valores desde `2` a `x-1`. Crea una variable `divisible`  que tenga por defecto valor `False` y asigne el valor `True` si a lo largo de la iteración encuentra un número natural divisible. Puedes usar el operador modulo `a % b` para saber si un numero `b` es divisible por `a`.

In [11]:
x=15
divisible=False
for i in range(2,x):
    if(x%i==0):
        divisible=True
        break
print("Es primo:",not divisible)

Es primo: False


b) Convierte tu código anterior en una función que compruebe si el número del argumento es primo o no, devolviendo True is es primo y False si no es primo. Comprueba tu función con los valores 492366587, 492366585, 48947 y 2,


In [18]:
def es_primo(x):
    divisible=False
    for i in range(2,x):
        if(x%i==0):
            divisible=True
            break
    return not divisible

pruebas=[492366587, 492366585, 48947 , 2]

[print(f"El nº {prueba} es primo:{es_primo(prueba)}") for prueba in pruebas]

True
El nº 492366587 es primo:True
El nº 492366585 es primo:False
El nº 48947 es primo:True
El nº 2 es primo:True


[None, None, None, None]

c) En el cálculo de la función anterior, una vez se ha encontrado un número que es divisible dentro del rango ya no tiene sentido comprobar el resto de números del rango. Por ejemplo si 10 ya es divisble entre 2, ya no hace falta probar de 3 en adelante pues ya sabemos que el número no es primo. 

Modifica la función anterior de la siguiente forma: 
- Una vez se encuentra el divisor, la iteración se interrumpe para no probar el resto de enteros. 
- La función devuelve
    - **Si es primo**: True
    - **Si no es primo**, el primer divisor mayor que 1.
    
Puedes hacer uso del comando *break* dentro de un bucle para interrumpir este, puedes consultar más información sobre break en la documentación de python [aquí](https://docs.python.org/2/tutorial/controlflow.html).

Comprueba tu función con los valores 492366585, 492366587, 48947 y 2,

In [ ]:
# Respuesta : (apartado anterior)

### Ejercicio 2

La Covid-19 es una enfermedad producida por la infección del virus SARS-CoV-2. La infección es transmisible de persona a persona y su contagiosidad depende de la cantidad del virus en las vías respiratorias. Si cada persona contagiada transmite la enfermedad a $\beta$ contactos en promedio por periodo de tiempo $t$, es posible estimar la evolución del contagio con un modelo matemático sencillo.

Para $t=1$ día, las transmisiones en España se han estimado a partir de su histórico de las semanas de Febrero y Marzo del 2020 una $\beta = 0.35$ transmissiones por día por infectado.

Durante un periodo de tiempo (por ejempo un día $d$) la tasa de nuevos contagios se puede estimar como  una proporción al número de contagiados del periodo anterior $N$: 

$ \Delta N = N_{1} - N = \beta \cdot $ (1)

Por tanto, podemos proyectar el número futuro de afectados como 

$ N_{1} = N + \beta \cdot N = (1+\beta) \cdot $ (2) 

En dos días:

$ N_{2} = (1+\beta) \cdot N_{1} = (1+\beta)^2 \cdot $  (3)

Y en general en D días tendremos 

$ N_{D} = (1+\beta)^D \cdot N$  (4)
 
Asumiendo este sencillo modelo: 

a) Implementa una función de dos parámetros (N: población infectada inicial, D: número de días), que devuelva el cálculo de afectados para D días siguiendo la ecuación (4). Suponiendo una población afectada de 4250 (población afectada en españa a día 13 de Marzo de 2020), usa la función para calcular la población estimada en 1, 2, 7 y 30 días. 

In [20]:
def fcovid(N,D):
    """
    Funcion que estima el numero de contagiados que va a haber en un periodo de tiempo.

    args.
    -----
    N: int; poblacion infectada inicial.
    D: int; días a estimar.

    return.
    -------
    C: int; número de contagiados.
    """
    beta=0.35

    C=((1 + beta)**D) * N

    return C

afectados0=4250
dias_est=[1,2,7,30]    
[print(f"Contagiados en {dias} días: {fcovid(afectados0,dias)}") for dias in dias_est]            

Contagiados en 1 días: 5737.5
Contagiados en 2 días: 7745.625000000001
Contagiados en 7 días: 34731.64149433595
Contagiados en 30 días: 34546335.38087164


[None, None, None, None]

b) Sabiendo que los Servicios de Medicina Intensiva (SMI) disponen de 3363 camas para enfermos graves, y suponiendo que un 10% de los afectados por el covid-19 requerirán de SMI y una supervivencia del 2,5% (Exitus), escribe un código que calcule:
- El día en curso (Día)
- El total de afectados por el virus para cada día d (Afectados)
- El total de ingresados en SMI por el virus para cada día d (Críticos)
- El total de Exitus por el virus para cada día d (Exitus)
- Si los servicios de SMI no pueden aceptar los ingresados para cada día $d$ (Estado: indicando Saturación/No Saturación)

Imprime en pantalla la información de cada día durante una simulación de tres semanas, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una $\beta = 0.35$ constante. 

In [194]:
camas=3363
graves=0.1
exitus=0.025

resultado1={
    "dia":[i for i in range(1,3*7+1)],
    "afectados":[fcovid(afectados0,dias) for dias in range(1,3*7+1)],
    "criticos":[fcovid(afectados0,dias)*graves for dias in range(1,3*7+1)], 
    "exitus":[fcovid(afectados0,dias)*graves*exitus for dias in range(1,3*7+1)],
}
resultado1["estado"]=["No saturacion" if(camas-resultado1['criticos'][i-1]>0) else "Saturacion" for i in range(1,3*7+1)]


[print(f"Dia {resultado1['dia'][i]} afectados: {resultado1['afectados'][i]} criticos: {resultado1['criticos'][i]} exitus: {resultado1['exitus'][i]} estado: {resultado1['estado'][i]} " ) for i in range(3*7)]           

Dia 1 afectados: 5737.5 criticos: 573.75 exitus: 14.34375 estado: No saturacion 
Dia 2 afectados: 7745.625000000001 criticos: 774.5625000000001 exitus: 19.364062500000003 estado: No saturacion 
Dia 3 afectados: 10456.593750000002 criticos: 1045.6593750000002 exitus: 26.141484375000005 estado: No saturacion 
Dia 4 afectados: 14116.401562500005 criticos: 1411.6401562500005 exitus: 35.29100390625001 estado: No saturacion 
Dia 5 afectados: 19057.142109375007 criticos: 1905.7142109375009 exitus: 47.642855273437526 estado: No saturacion 
Dia 6 afectados: 25727.14184765626 criticos: 2572.714184765626 exitus: 64.31785461914066 estado: No saturacion 
Dia 7 afectados: 34731.64149433595 criticos: 3473.164149433595 exitus: 86.82910373583988 estado: Saturacion 
Dia 8 afectados: 46887.71601735354 criticos: 4688.771601735354 exitus: 117.21929004338386 estado: Saturacion 
Dia 9 afectados: 63298.416623427285 criticos: 6329.841662342729 exitus: 158.24604155856824 estado: Saturacion 
Dia 10 afectados: 85

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

c) Convierte el código anterior en una función que genere un archivo de texto con nombre `output.txt`, siguiendo este formato: 
```
Dia, Afectados, Críticos, Exitus, Estado
0, 4250, 425,  106, No Saturación
1, 5737, 573,  143, No Saturación
2, 7745, 774,  193, No Saturación
...
```
Con los parámetros de entrada $N$, $D$, $\beta$, camas SMI.

In [223]:
def datos_covid(N,D,camas):

    graves=0.1
    exitus=0.025
    arch=open("output.txt","w")

    resultado={

        "dia":[i for i in range(1,D+1)],
        "afectados":[fcovid(N,dias) for dias in range(1,D+1)],
        "criticos":[fcovid(N,dias)*graves for dias in range(1,D+1)], 
        "exitus":[fcovid(N,dias)*graves*exitus for dias in range(1,D+1)],
    }
    resultado["estado"]=[" No saturacion" if(camas-resultado['criticos'][i-1]>0) else " Saturacion" for i in range(1,3*7+1)]

    arch.write("Dia, Afectados, Criticos, Exitus, Estado \n")
    [arch.write(f"{resultado['dia'][i]} {resultado['afectados'][i]} {resultado['criticos'][i]} {resultado['exitus'][i]}{resultado['estado'][i]}\n") for i in range(D)]

    return arch
                

In [224]:
archivo=datos_covid(4250,3*7,3363)

In [225]:
with open("output.txt","r") as archivo:
    print(archivo)

<_io.TextIOWrapper name='output.txt' mode='r' encoding='UTF-8'>


### Ejercicio 3

Dado el siguiente diccionario:

In [ ]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

Escribid una función que pregunte al usuario que introduzca el nombre de una persona y muestre por pantalla el nombre de la persona y su teléfono. 

Tened en cuenta que:

- La función debe controlar que el valor introducido por el usuario es un nombre que existe en el diccionario. En caso contrario, mostrará un mensaje de error ("El nombre introducido no corresponde a ninguna persona") y devolverá el valor False.
- Debéis tener en cuenta que el nombre de las personas que nos pasan por parámetro puede ser en minúsculas, mayúsculas o una combinación de ambas, y que debemos encontrar el número de teléfono aunque la capitalización de la cadena entrada por el usuario no sea exactamente la misma que hemos almacenado en el diccionario.
- Suponed que  no hay acentos en los nombres.

Nota 1: Para realizar la actividad, tendréis que capturar un texto que entrará el usuario. Consultad la [documentación oficial de la función input](https://docs.python.org/3/library/functions.html#input) para ver cómo hacerlo.

Nota 2: También tendréis que pensar cómo tratar el hecho de que el usuario pueda utilizar mayúsculas y minúsculas en la escritura del nombre en el diccionario. ¡Os animamos a usar un buscador para intentar encontrar alguna alternativa para resolver este subproblema! ¡Recordad citar las referencias que hayáis usado para resolverlo!


In [36]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

def telefono(nombre,d):
    """
    Funcion que indica el número de telefono de una persona perteneciente a un listado.

    args.
    -----
    nombre: str; nombre de la persona.
    d: dict; listado de nombres y telefonos.

    return.
    -------
    n_telef: int; numero de telefono (o bool; /False/ si nombre no pertenece al listado)
    """
    n_telef=False
    
    for k,v in d.items():
        if(nombre.capitalize()==k):
            n_telef=v
            break

    if(n_telef==False):
        print("El nombre introducido no corresponde a ninguna persona")

    return n_telef
            

In [42]:
print("Introduzca nombre:\n")

nombre=input()
print(nombre)
telefono(nombre,d)

Introduzca nombre:

alex


344334443

###  Ejercicio 4

Python dispone de un **idiom** muy útil conocido como `list comprehension`. Utilizando este **idiom**, proporcionad una expresión que devuelva las listas siguientes.

Nota: Para realizar esta actividad necesitaréis investigar qué son las `list comprehension` y qué sintaxis utilizan. Para ello, se recomienda en primer lugar que utilicéis un buscador para encontrar información genérica sobre esta construcción. Después, os recomendamos que consultéis stackoverflow para ver algunos ejemplos de problemas que se pueden resolver con esta construcción.


[stackoverflow](https://stackoverflow.com/) es un sitio de preguntas-y-respuestas muy popular entre programadores. Veréis que para la gran mayoría de las dudas que tengáis, habrá alguien que ya les habrá tenido (y consultado) anteriormente! Así pues, más allá de preguntar vosotros mismos las dudas allí (nosotros ya tenemos el foro del aula para ello!), consultar esta web os permitirá ver qué soluciones proponen otros programadores a estas dudas. A menudo habrá más de una solución a un mismo problema, y podréis valorar cuál es la más adecuada para vuestro problema.

Para ver ejemplos de problemas que son adecuados para resolver con **list comprehensions**, os recomendamos leer las siguientes páginas:
* https://stackoverflow.com/questions/12555443/squaring-all-elements-in-a-list
* https://stackoverflow.com/questions/18551458/how-to-frame-two-for-loops-in-list-comprehension-python
* https://stackoverflow.com/questions/24442091/list-comprehension-with-condition
* https://stackoverflow.com/questions/41676212/i-want-to-return-only-the-odd-numbers-in-a-list
* https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension


a) Una lista con los valores $4 x^2$ donde $x$ es cada uno de los números de la lista `list_1`:

In [43]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

[4*x**2 for x in list_1]

[4, 16, 36, 64, 100, 144, 196, 256, 324]

b) Una lista con los valores $x/(x+1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [44]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

[x/(x+1) for x in list_1]

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9]

c) Una lista con los valores $4x^2/(4x^2-1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [45]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

[(4*x**2)/((4*x**2)-1) for x in list_1]


[1.3333333333333333,
 1.0666666666666667,
 1.0285714285714285,
 1.0158730158730158,
 1.0101010101010102,
 1.006993006993007,
 1.005128205128205,
 1.003921568627451,
 1.0030959752321982]

### Ejercicio 5

El siguiente ejercicio consiste en pasar un número en base 16 (hexadecimal, 0-9/A-F) a base 10 (decimal). Para hacerlo, debéis crear una **función** que dado un _string_ que representa un número en hexadecimal, por ejemplo, `AE3F`, devuelva el número 
natural correspondiente. En este caso, el resultado sería `44607`.

In [87]:

def conversor_HaD(h):
    """
    Funcion que realiza la conversión de hexadecimal a decimal.

    args.
    -----
    h: str; numero hexadecimal (base 16)
    
    return.
    -------
    d: int; numero convertido a decimal (base 10)
    """
    d=0
    sustituye=['A','B','C','D','E','F']

    hexa={sustituye[k]:k+10 for k in range(len(sustituye))}

    for i,hi in enumerate(h):
        if(sustituye.count(hi)==0):
            d+=int(hi)*16**(len(h)-i-1)
        else:
            d+=hexa.get(hi)*16**(len(h)-i-1)
    return d
       


In [88]:
conversor_HaD("AE3F")

44607

### Ejercicio 6

Las excepciones son errores detectados en tiempo de ejecución. Pueden y deben ser manejadas por el programador para minimizar el riesgo de que un determinado programa falle de forma no controlada. Escribid, en lenguaje Python, cómo generar y capturar la siguiente excepción: **ZeroDivisionError**.

In [92]:
a=1
b=0
try:
    res=a/b
    print(res)
except ZeroDivisionError as err:
    print('Error:', err)

Error: division by zero


### Ejercicio 7

Completad el código necesario para calcular el número de vocales y de consonantes respectivamente de un texto.

In [109]:
import string

def contar_vocales_y_consonantes(texto):
    # Cuenta las vocales contenidas en el string texto y también las consonantes.
    num_vocales = 0
    num_consonantes = 0

    
    texto2=texto.translate(str.maketrans('', '', string.punctuation))
    print(texto2)

    num_espacios = texto2.count(' ')
    vocales="AEIOU"

    for letra in texto2:
        for i in vocales:
            if (letra.upper()==i):
                num_vocales+=1
    print(num_espacios)
    num_consonantes=len(texto2)-num_vocales-num_espacios

    return num_vocales, num_consonantes

texto = "Orbiting Earth in the spaceship, I saw how beautiful our planet is. \
            People, let us preserve and increase this beauty, not destroy it!"

num_vocales, num_consonantes = contar_vocales_y_consonantes(texto)
print("El número de vocales es %d." % num_vocales)
print("El número de consonantes es %d." % num_consonantes)

Orbiting Earth in the spaceship I saw how beautiful our planet is             People let us preserve and increase this beauty not destroy it
34
El número de vocales es 44.
El número de consonantes es 62.


### Ejercicio 8

Escribid una función que dada una lista de planetas del sistema solar, pregunte al usuario que introduzca una posición y muestre el plante correspondiente a dicha posición. Por ejemplo, si tenemos la siguiente lista: `['Mercurio', 'Venus', 'Tierra', 'Marte']` y el usuario nos ha introducido la posición `3`, hemos de mostrar como resultado por pantalla: `Tierra`.

Consideraciones:

- La posición que introduzca el usuario tiene que ser un número entero estrictamente positivo.
- La función debe controlar el acceso a una posición fuera de la lista mediante una **excepción**. Por ejemplo, en el caso anterior debemos mostrar una mensaje de error si el usuario pide acceder a la posición 10.

In [122]:
def planeta(planetas):
    try:
        indice=int(input())
        res=planetas[indice-1]
    except IndexError as err:
        print('Error:', err)
        res=False
    return res


planetas=['Mercurio', 'Venus', 'Tierra', 'Marte']
print(planeta(planetas))


Error: list index out of range
False


### Ejercicio 9

Dada una lista de planetas del sistema solar, determinad cuales de estos planetas tienen una masa superior a la de la Tierra. Por ejemplo, si la lista inicial es `['Venus', 'Marte', 'Saturno']`, el resultado que mostraríamos por pantalla sería `['Saturno']` ya que el planeta Saturno tiene una masa `95.2` veces superior a la Tierra.

Consideraciones:

- Debéis tener en cuenta que el nombre de los planetas que nos pasan por parámetro puede estar en minúsculas, mayúsculas o una combinación de ambas.
- Podéis asumir que no habrá acentos en el nombre de los planetas.
- Debéis determinar aquellos planetas que tiene una massa estrictamente superior a la de la Tierra.
- No habrá planetas repetidos en la lista que nos pasan por parámetro.

In [5]:
masas = {'Mercurio': 0.06, 'Venus': 0.82, 'Tierra': 1, 'Marte': 0.11, 'Jupiter': 317.8, 
          'Saturno': 95.2, 'Urano': 14.6, 'Neptuno': 17.2, 'Pluto': 0.0022}

In [126]:
def planetas_mas_grandes_que_Tierra(planetas):
    """
    Planetas con una masa superior a la de la Tierra
    """

    masas = {'Mercurio': 0.06, 'Venus': 0.82, 'Tierra': 1, 'Marte': 0.11, 'Jupiter': 317.8, 
          'Saturno': 95.2, 'Urano': 14.6, 'Neptuno': 17.2, 'Pluto': 0.0022}

    planetas_masa_superior = []

    for planeta in planetas:
        if (masas.get(planeta.capitalize())>masas.get('Tierra')):
            planetas_masa_superior.append(planeta.capitalize())
    if (planetas_masa_superior==[]):
        planetas_masa_superior="Ninguno de los planetas dados tiene masa superior a la Tierra"

    return planetas_masa_superior

# Ejemplos de uso de la función anterior
print(planetas_mas_grandes_que_Tierra(['Venus', 'Mercurio', 'Marte']))
print(planetas_mas_grandes_que_Tierra(['Jupiter', 'Saturno', 'Pluto']))
print(planetas_mas_grandes_que_Tierra(['urano', 'tierra', 'neptuno', 'marte', 'Venus']))
print(planetas_mas_grandes_que_Tierra(['Tierra', 'MeRcUrIo', 'PLUTO', 'SATURNO']))

# Podéis añadir más ejemplos si lo consideráis oportuno

Ninguno de los planetas dados tiene masa superior a la Tierra
['Jupiter', 'Saturno']
['Urano', 'Neptuno']
['Saturno']


### Ejercicio 10

Dada una cadena de caracteres, `s`, de longitud `n` y un número entero positivo `k`, siendo `k` un divisor de `n`, podemos dividir la cadena `s` en `n / k` sub-cadenas de la misma longitud.

Escribid una función que, dada una cadena `s` y un número entero `k`, devuelva las `n/k` sub-cadenas teniendo en cuenta las siguientes consideraciones:

- El orden de los caracteres en las sub-cadenas debe ser el mismo que en la cadena original.
- Todos los caracteres de las sub-cadenas deben aparecer una única vez. Es decir, si un caracter se repite dentro de una sub-cadena, sólo hemos de mostrar la primera ocurrencia.

Por ejemplo, si tenemmos
<code>
s = AABCCAADA
k = 3
</code>

el resultado a mostrar por pantalla sería:
<code>
AB
CA
AD
</code>

Tenemos que la longitud de la cadena es 9 y por lo tanto, podemos formar 3 sub-cadenas:

`AAB -> AB` (el caracter A se repite dos veces)

`CCA -> CA` (el caracter C se repite dos veces)

`ADA -> AD` (el caracter A se repite dos veces)

In [183]:
def no_replicas(cad):
    return "".join(dict.fromkeys(cad))


def subcadenas(s,n):

    lon=len(s)
    div=int(lon/n)
        
    ns=[s[ini:ini+div] for ini in range(0,lon,div)]
    
    for i,c in enumerate(ns):
        ns[i]=no_replicas(c)

    return ns

In [185]:
s = 'AABCCAADA'
k = 3
subcadenas(s,k)

['AB', 'CA', 'AD']